version: 0.0
os: linux

files:             
  - source: ./webapp/spring-login-master/target/cloudApp.war
    destination: /opt/tomcat/webapps

hooks:
  AfterInstall:
   - location: ./afterInstall.sh
     timeout: 180
     runas: centos
  ApplicationStart:
   - location: ./applicationStart.sh
     timeout: 180
     runas: centos
